/**
 * User-facing language for the team workspace.
 * Keep tone warm, clear, and jargon-light — everyone reads this.
 */

export const brand = {
  /** Short name in sidebar / login */
  short: 'Team space',
  /** Full product name */
  full: 'AfriVate Team Space',
  metaDescription:
    'Plan your work, share weekly updates, request time off, and stay in the loop with your colleagues — all in one place.',
  /** Aligns with AfriVate brand voice */
  tagline: 'Innovation · Elevation · Technology',
  headOffice:
    'Head office: AfriVate Technologies Ltd · RC: 9210092 · Abuja, Nigeria',
} as const

/** Side nav & mobile bar — keep concise */
export const nav = {
  home: 'Home',
  myWork: 'My work',
  weeklyUpdate: 'Weekly update',
  gettingStarted: 'Getting started',
  updates: 'Updates',
  timeOff: 'Time off',
  people: 'People',
  resources: 'Resources',
  shoutOuts: 'Shout-outs',
  whatsOn: "What's on",
  workspaceAdmin: 'Admin',
  inbox: 'Inbox',
  search: 'Search',
  notes: 'Notes',
} as const

/** How we describe roles on profile cards, headers, etc. */
export const roleTitles = {
  staff: 'Team member',
  assistant_lead: 'Assistant lead',
  team_lead: 'Team lead',
  hr: 'People & culture',
  admin: 'Administrator',
} as const

/** Common actions */
export const actions = {
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  signIn: 'Sign in',
  signOut: 'Sign out',
  viewAll: 'View all',
  learnMore: 'Learn more',
} as const

export const pages = {
  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to your AfriVate team portal.',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    signInHelp:
      'Already have an account? Sign in above. New to AfriVate? Use Request access to create one.',
    requestAccessCta: 'Request access',
  },
  requestAccess: {
    title: 'Request access',
    subtitle:
      'Create your account here. We will notify People & Culture to review and approve you.',
    submitLabel: 'Create account & request access',
    nameLabel: 'Your name',
    namePlaceholder: 'e.g. Emmanuel Okpiaifo',
    emailHint: 'Work or personal email — use the same address to sign in later.',
    passwordHint: 'At least 8 characters.',
    confirmEmailSuccess:
      'Account created! Confirm your email, then sign in. If your account is still pending, you can send your access request from the next screen.',
  },
  home: {
    title: 'Home',
    subtitle:
      "Your week at a glance — deadlines, time off, company updates, and what's on today.",
    roleLine: (jobTitle: string, department: string) => `${jobTitle} · ${department}`,
    quickAddTask: 'New task',
    quickTimeOff: 'Request time off',
    quickWeekly: 'Weekly update',
    stats: {
      dueToday: 'Due today',
      dueTodayHint: "Open tasks with today's date",
      pendingTimeOff: 'Time off in review',
      pendingTimeOffHint: 'Waiting on approval',
      eventsThisWeek: 'This week',
      eventsThisWeekHint: 'Meetings & gatherings in the next 7 days',
      newUpdates: 'New updates',
      newUpdatesHint: "Company posts you haven't opened yet",
    },
    onboardingBanner: (watched: number, total: number) =>
      `You've completed ${watched} of ${total} welcome videos`,
    onboardingCta: 'Continue learning',
    recentUpdates: 'Latest updates',
    todaySchedule: 'Today',
    emptyUpdates: 'No updates yet',
    emptyUpdatesBody: "When your People & culture team posts news, it'll show up here.",
    emptyDay: 'Nothing scheduled',
    emptyDayBody: "Enjoy the calm — or add something in What's on.",
    tipTitle: 'Small habits help the team',
    tipBody:
      'Sending your weekly update on time keeps leads informed. Requesting time off here (instead of chat) gives everyone a clear record.',
  },
  tasks: {
    title: 'My work',
    subtitle:
      "Track what you're doing, what's blocked, and what's due — switch between board and week views anytime.",
    board: 'Board',
    week: 'Week',
    list: 'List',
    filterScope: 'Focus',
    scopeRelated: 'Owned & assigned',
    scopeOwned: 'I own',
    scopeAssigned: 'Assigned to me',
    newTask: 'New task',
    searchPlaceholder: 'Search by title or notes…',
    filterStatus: 'Status',
    filterPriority: 'Priority',
    sortBy: 'Sort',
    sortDueSoon: 'Due date (soonest first)',
    sortDueLater: 'Due date (latest first)',
    sortUpdated: 'Recently updated',
    statusAll: 'All statuses',
    priorityAll: 'All priorities',
    clearFilters: 'Clear filters',
    statusUpNext: 'Up next',
    statusInProgress: 'In progress',
    statusComplete: 'Complete',
    statusStuck: 'Stuck',
    priorityUrgent: 'Urgent',
    priorityNormal: 'Normal',
    priorityLater: 'When you can',
    blockedHelp: "What's blocking you",
    blockersPlaceholder: 'Anything we should know?',
    updateStatus: 'Move to…',
    detailChangeStatus: 'Change status',
    statTotal: 'All items',
    statInProgress: 'In progress',
    statDone: 'Complete',
    statOverdue: 'Past due',
    showingCount: 'Showing {n} of {total} items',
    columnEmpty: 'Nothing here yet',
    filteredEmptyTitle: 'Nothing matches',
    filteredEmptyBody: 'Try clearing filters or changing your search.',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    thisWeekLabel: 'This week',
    jumpToThisWeek: 'Jump to this week',
    weekNoItems: 'Nothing due',
    formEditTitle: 'Edit item',
    formNewTitle: 'New item',
    formTitleLabel: 'Title',
    formTitlePlaceholder: 'What needs to get done?',
    formDescriptionLabel: 'Notes',
    formDescriptionPlaceholder: 'Optional — context, steps, links, or @mention someone',
    formAssigneeLabel: 'Assigned to',
    assigneeOwnerOnly: 'Owner (me, if new)',
    mentionHint: 'Tip: type @FirstName in notes to ping teammates.',
    listOverdue: 'Overdue',
    listDueToday: 'Due today',
    listThisWeek: 'Later this week',
    listLater: 'After this week',
    listNoDue: 'No due date',
    formStatusLabel: 'Status',
    formPriorityLabel: 'Priority',
    formCategoryLabel: 'Category',
    formDueLabel: 'Due date',
    formHoursLabel: 'Hours logged',
    formEstimateLabel: 'Estimated hours',
    detailDescription: 'Notes',
    detailBlockers: 'Blockers',
    detailActivity: 'Activity',
    detailHoursLogged: 'Hours logged',
    detailEstimated: 'Estimated',
    prioritySuffix: 'priority',
    deleteConfirm: 'Delete this item?',
    delete: 'Delete',
    edit: 'Edit',
    emptyTasksTitle: 'Nothing here yet',
    emptyTasksBody: "Add something to track what you're working on.",
    tableTask: 'Item',
    tableStatus: 'Status',
    tableCategory: 'Category',
    tableAssignee: 'Assignee',
    tableDue: 'Due',
    tableHours: 'Hours',
    saveChanges: 'Save changes',
    createTask: 'Create',
    noDue: 'No due date',
  },
  inbox: {
    title: 'Inbox',
    subtitle: 'Shout-outs, assignments, and mentions in one place.',
    markAllRead: 'Mark all read',
    empty: "You're all caught up",
    emptyBody:
      'When someone shouts you out, assigns you a task, or @mentions you in notes, it will show up here.',
  },
  search: {
    title: 'Search',
    subtitle: 'Find people, company updates, and tasks you have access to.',
    placeholder: 'Search people, updates, tasks…',
    people: 'People',
    updates: 'Updates',
    tasks: 'Tasks',
    noResults: 'No matches',
    hint: 'Try another name, keyword, or task title.',
  },
  notes: {
    title: 'Notes',
    subtitle: 'Shared pages for meeting notes, plans, and team knowledge.',
    newNote: 'New page',
    allNotes: 'Pages',
    titleLabel: 'Title',
    bodyLabel: 'Note',
    bodyPlaceholder: 'Type here — teammates with access can see your changes.',
    emptyTitle: 'Pick or create a page',
    emptyBody: 'Write specs, meeting notes, and guides. Share with your team or keep pages private.',
    emptyList: 'No pages yet',
    delete: 'Delete',
    deleteConfirm: 'Delete this page for everyone who has access?',
    alsoHere: 'Also editing:',
    footerHint: 'Last edited by',
    sharedLabel: 'Sharing',
    share: 'Share',
    shareViewOnly: 'View sharing & copy link',
    shareReadOnlyHint:
      'You can see who has access and copy a share link. To change settings, ask the page owner or an admin.',
    shareLinkToPage: 'Link to this page',
    shareLinkCopyHelp:
      'Send this link to someone who should open this page. They must sign in first.',
    shareNoLinkActive:
      'Link sharing is off for this page. Ask the owner to turn it on in Share settings.',
    sharePageOwner: 'Page owner',
    shareInvitedEmailsList: 'Email invites',
    shareClose: 'Close',
    shareTitle: 'Share page',
    shareIntro: 'Choose who can open this page.',
    shareWho: 'Who has access',
    shareCancel: 'Cancel',
    shareSave: 'Apply',
    scopePrivate: 'Private (only me)',
    scopeWorkspace: 'Everyone in the company',
    scopeDepartments: 'Specific departments',
    scopeTeams: 'Specific teams',
    scopePeople: 'Specific people',
    sharePrivate: 'Only you',
    shareWorkspace: 'Everyone in the company',
    sharePickDept: 'Pick at least one department',
    sharePickTeam: 'Pick at least one team',
    sharePickPeople: 'Pick at least one person',
    sharePeopleCount: 'people',
    departmentsPick: 'Departments',
    teamsPick: 'Teams',
    peoplePick: 'People',
    shareInviteEmails: 'Invite by email',
    shareInviteEmailsHint: 'People with these emails can view this page when they sign in.',
    shareInvitePlaceholder: 'name@company.com',
    shareInviteAdd: 'Add',
    shareLinkSection: 'Link sharing',
    shareLinkHelp: 'Turn on a link anyone with the URL can use (they still sign in to the portal).',
    shareLinkOn: 'Link on',
    shareLinkOff: 'Link off',
    shareLinkCopy: 'Copy link',
    shareLinkRegenerate: 'Create a new link',
    shareLinkCopied: 'Copied',
    invitedEmails: 'email invites',
    blockMenuTitle: 'Turn into…',
    mentionMenuLabel: 'People',
    mentionEmpty: 'No matching people',
    emojiPickerTitle: 'Pick an icon',
    gripHint: 'Drag to reorder',
    notionHint: 'Pages',
    subPage: 'Add page',
    addBlock: 'Insert',
    blockType: 'Block type',
    removeBlock: 'Remove block',
    blockPh: "Write, or type '/' for blocks…",
    headingPh: 'Heading',
    calloutPh: 'Callout text',
    iconLabel: 'Icon',
    untitledPlaceholder: 'Untitled',
    slashHint: "Type '/' to open the block menu.",
    slashMenuLabel: 'Block types',
    slashMenuSection: 'Blocks',
    openBlockMenu: 'Block menu',
    todoDoneLabel: 'Done',
    todoCompletedOn: 'Completed',
    remoteNoteTitle: 'This page was updated by someone else',
    remoteNoteBody: 'Load their version to continue together, or keep editing to save your changes.',
    remoteNoteLoadLatest: 'Load latest',
    remoteNoteDismiss: 'Dismiss',
    addBlockBelow: 'Add block',
    appendBlock: 'Add a block',
    iconPrompt: 'Paste or type an emoji for this page',
    statusLive: 'Editing together',
    statusConnecting: 'Connecting…',
    statusLocalTabs: 'This device only',
    statusError: 'Sync unavailable',
    statusSolo: 'Offline',
    liveSyncHint: 'When others edit this page at the same time, you will see their changes here.',
  },
  weeklyUpdate: {
    title: 'Weekly update',
    subtitle:
      'A quick reflection each week helps your lead support you and keeps priorities visible. Most people send this on Friday.',
    tabThisWeek: 'This week',
    tabHistory: 'Past updates',
    tabTeam: "Team's updates",
    submittedTitle: "Thanks — you're all set",
    editButton: 'Edit my update',
  },
  gettingStarted: {
    title: 'Getting started',
    subtitle: 'Videos and a simple checklist so your first weeks feel less overwhelming.',
    tabVideos: 'Videos',
    tabChecklist: 'Checklist',
    tabAdmin: 'Manage content',
  },
  updates: {
    title: 'Updates',
    subtitle: 'News and notes from leadership and People & culture — newest first.',
    newPost: 'New update',
    searchPlaceholder: 'Search updates…',
    markAllRead: 'Mark all as read',
    unreadOnly: 'Unread only',
    priorityFYI: 'FYI',
    priorityHeadsUp: 'Heads up',
    priorityAction: 'Action needed',
    priorityAll: 'All levels',
    priorityFilterLabel: 'Urgency',
    openedCount: '{n} opened',
    everyone: 'Everyone',
    unknownAuthor: 'Unknown',
    emptyFilteredTitle: 'Nothing matches',
    emptyFilteredBody: 'Try a different search or clear the filter.',
    emptyFeedTitle: 'No updates yet',
    emptyFeedBodyPoster: "Share the first post when you're ready.",
    emptyFeedBodyMember:
      "When People & culture or your leads share news, it'll show up here.",
    formNewTitle: 'New update',
    formEditTitle: 'Edit update',
    formTitleLabel: 'Title',
    formTitlePlaceholder: 'Short, clear headline',
    formBodyLabel: 'Message',
    formBodyPlaceholder: "What's changing, what people should know, and any ask.",
    formAudienceLabel: 'Who should see this',
    formPriorityLabel: 'How urgent is this',
    deleteConfirm: 'Delete this update?',
    editAria: 'Edit update',
    deleteAria: 'Delete update',
  },
  timeOff: {
    title: 'Time off',
    subtitle: 'See your balances, send a request, and track approvals in one place.',
    requestCta: 'New request',
    balancesExplainer:
      'Balances show approved days this year. Your full leave policy is with People & culture.',
  },
  people: {
    title: 'People',
    subtitle:
      "Who's who at AfriVate — roles, teams, and how to reach coworkers on work email. Update your own photo and contact details so the directory stays useful for everyone.",
    searchPlaceholder: 'Search by name, email, role, department, or skill…',
    allDepartments: 'All departments',
    directoryNote:
      'Profiles are for internal use. For the public site and HQ address, see afrivate.org.',
    presenceNote:
      'Green dots show when someone is available. Your status updates for colleagues when you change it here.',
    sendEmail: 'Send email',
    copyEmail: 'Copy address',
    copied: 'Copied',
    openProfile: 'Profile',
    organization: 'Organization',
    reportsTo: 'Reports to',
    workLocation: 'Work location',
    accessRole: 'Portal access',
    memberSince: 'Member since',
    about: 'About',
    skills: 'Skills',
    contact: 'Contact',
    pronouns: 'Pronouns',
    linkedin: 'LinkedIn',
    noMatches: 'No matches',
    noMatchesHint: 'Try another search or choose a different department.',
    editProfile: 'Edit my profile',
    profileEditIntro:
      "Help teammates recognize you. Job title, department, and reporting line are kept accurate by People & culture — you can refresh your photo, how to reach you, and a short intro.",
    profilePhotoSection: 'Profile photo',
    profilePhotoHelp:
      'Upload a photo the same way announcement images go to company hosting, or paste a link to a square image.',
    profilePhotoUpload: 'Upload photo',
    profilePhotoUploading: 'Uploading…',
    profilePhotoUrlLabel: 'Image link (optional)',
    profilePhotoUrlPlaceholder: 'https://…',
    profileAboutHelp:
      "Optional — what you're working on, how you like to collaborate, or topics you're happy to help with.",
    phoneLabel: 'Phone',
    phoneHint: 'Shown in the directory — work or mobile, whichever you prefer colleagues to use.',
    linkedinHint: "Optional. Only add this if you're comfortable listing it for coworkers.",
    skillsHint: 'Comma-separated — tools, topics, or areas you can help with.',
    emailSubject: (firstName: string) => `${firstName} — message from AfriVate Team Space`,
    emailBody: (recipientFirst: string, senderName: string) =>
      `Hi ${recipientFirst},\n\n\n— ${senderName}`,
  },
  resources: {
    title: 'Resources',
    subtitle: 'Handbooks, templates, brand files, and guides your team shares here.',
    upload: 'Upload a file',
  },
  shoutOuts: {
    title: 'Shout-outs',
    subtitle: 'Celebrate teammates — a few words go a long way.',
    give: 'Give a shout-out',
  },
  whatsOn: {
    title: "What's on",
    subtitle: 'Team meetings, all-hands, and events that matter to you.',
    newEvent: 'Add event',
    list: 'List',
    calendar: 'Calendar',
    schedule: 'Schedule',
    google: 'Google Calendar',
    googleTabIntro:
      "This view embeds your team's public Google Calendar. Your workspace administrator provides the calendar link.",
    externalSyncError: 'Could not load synced calendar events. Check the server feed URL.',
    externalBadge: 'Synced',
    scheduleInteractHint:
      'Click a day or drag across dates to add an event. Switch to Week or Day to pick times. Hover events for times; click for details.',
    scheduleViewHint:
      'Use Month, Week, Day, or Agenda in the toolbar. Hover an event for its time; click for details. Click a day number to jump to that day.',
  },
  workspaceAdmin: {
    title: 'Admin',
    subtitle:
      'Manage people, company updates, time off, welcome content, and weekly summaries.',
    sections: {
      people: 'People & access',
      updates: 'All updates',
      timeOff: 'Time off',
      onboarding: 'Welcome content',
      weeklyDigest: 'Weekly updates digest',
    },
  },
} as const

export const layout = {
  sidebarBadge: 'Team space',
  sidebarFootnote: (version: string) => `${version} · For team members`,
  authFooter: (year: number) => `© ${year} AfriVate Technologies · Employee portal`,
} as const
